spring.application.name=CinemaJavaSpringBootApplication
# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/cinemaDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# H2 Console (pentru debug - vezi datele in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf
spring.thymeleaf.cache=false

app.jwt.secret=CinemaSecretKey2024VeryLongAndSecureKeyForHMACSHA256AlgorithmMin256Bits
app.jwt.expiration-ms=86400000

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true